# Generated by Django 3.2.19 on 2023-10-04 19:33

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0006_merge_0005_auto_20221028_0347_0005_auto_20230408_1619"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="denormcontext",
            name="snapshot_no_id_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="denormcontext",
            name="snapshot_no_id_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="denormcontext",
            name="snapshot_no_id_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="denormcontext",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="denormcontext",
            name="snapshot_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="denormcontext",
            name="snapshot_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="ignoreautofieldssnapshotmodel",
            name="ignoreautofieldssnapshot_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="ignoreautofieldssnapshotmodel",
            name="ignoreautofieldssnapshot_delete",
        ),
        migrations.AddField(
            model_name="ignoreautofieldssnapshotmodelevent",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customeventmodel",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customeventwithcontext",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="custommodelevent",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="custommodelsnapshot",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customsnapshotmodel",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="denormcontextevent",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="denormcontexteventnoid",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventmodelevent",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nopghobjevent",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nopghobjsnapshot",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="snapshotimagefieldevent",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="snapshotmodeldtfieldevent",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="snapshotmodeldtfieldintfieldevent",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="snapshotmodelsnapshot",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="uniqueconstraintmodelevent",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usergroupsevent",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[(1, "Insert"), (2, "Update"), (3, "Delete"), (4, "Insertorupdate")],
                null=True,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="denormcontext",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_no_id_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tests_denormcontexteventnoid" ("fk_field_id", "id", "int_field", "pgh_context", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation") VALUES (NEW."fk_field_id", NEW."id", NEW."int_field", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB || \'{}\'::JSONB, NOW(), \'snapshot_no_id\', NEW."id", 1); RETURN NULL;',
                    hash="8e4114493bceeddd769179abc981584aaf93b7fc",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_no_id_insert_f9f15",
                    table="tests_denormcontext",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="denormcontext",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_no_id_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tests_denormcontexteventnoid" ("fk_field_id", "id", "int_field", "pgh_context", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation") VALUES (NEW."fk_field_id", NEW."id", NEW."int_field", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB || \'{}\'::JSONB, NOW(), \'snapshot_no_id\', NEW."id", 2); RETURN NULL;',
                    hash="62f764daa8819c3eb4bc0bfff5c37c4e2e8d8569",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_no_id_update_3c605",
                    table="tests_denormcontext",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="denormcontext",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_no_id_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tests_denormcontexteventnoid" ("fk_field_id", "id", "int_field", "pgh_context", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation") VALUES (OLD."fk_field_id", OLD."id", OLD."int_field", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB || \'{}\'::JSONB, NOW(), \'snapshot_no_id\', OLD."id", 3); RETURN NULL;',
                    hash="24426b9f96c86d6f3f69f363393920e36c8ff4a4",
                    operation="DELETE",
                    pgid="pgtrigger_snapshot_no_id_delete_6b6a3",
                    table="tests_denormcontext",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="denormcontext",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tests_denormcontextevent" ("fk_field_id", "id", "int_field", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation") VALUES (NEW."fk_field_id", NEW."id", NEW."int_field", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB || \'{}\'::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'snapshot\', NEW."id", 1); RETURN NULL;',
                    hash="02fef10a8aa4470de3b4233ea43fc0e36fb70420",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_37e9f",
                    table="tests_denormcontext",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="denormcontext",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tests_denormcontextevent" ("fk_field_id", "id", "int_field", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation") VALUES (NEW."fk_field_id", NEW."id", NEW."int_field", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB || \'{}\'::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'snapshot\', NEW."id", 2); RETURN NULL;',
                    hash="815523f490fe456b7841e9a1b8a21ea4db68be82",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_ca16a",
                    table="tests_denormcontext",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="denormcontext",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tests_denormcontextevent" ("fk_field_id", "id", "int_field", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation") VALUES (OLD."fk_field_id", OLD."id", OLD."int_field", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB || \'{}\'::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'snapshot\', OLD."id", 3); RETURN NULL;',
                    hash="ce172ab7c1cd3b1f59fa76314490e03ca4ae27d4",
                    operation="DELETE",
                    pgid="pgtrigger_snapshot_delete_6b3b9",
                    table="tests_denormcontext",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="ignoreautofieldssnapshotmodel",
            trigger=pgtrigger.compiler.Trigger(
                name="ignoreautofieldssnapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."my_char_field" IS DISTINCT FROM NEW."my_char_field" OR OLD."my_int_field" IS DISTINCT FROM NEW."my_int_field")',
                    func='INSERT INTO "tests_ignoreautofieldssnapshotmodelevent" ("created_at", "id", "my_char_field", "my_int_field", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "updated_at") VALUES (OLD."created_at", OLD."id", OLD."my_char_field", OLD."my_int_field", _pgh_attach_context(), NOW(), \'ignoreautofieldssnapshot\', OLD."id", 2, OLD."updated_at"); RETURN NULL;',
                    hash="f3720f1f5e3caf9aa67d3eabd642358f8844250a",
                    operation="UPDATE",
                    pgid="pgtrigger_ignoreautofieldssnapshot_update_767f2",
                    table="tests_ignoreautofieldssnapshotmodel",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="ignoreautofieldssnapshotmodel",
            trigger=pgtrigger.compiler.Trigger(
                name="ignoreautofieldssnapshot_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tests_ignoreautofieldssnapshotmodelevent" ("created_at", "id", "my_char_field", "my_int_field", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "updated_at") VALUES (OLD."created_at", OLD."id", OLD."my_char_field", OLD."my_int_field", _pgh_attach_context(), NOW(), \'ignoreautofieldssnapshot\', OLD."id", 3, OLD."updated_at"); RETURN NULL;',
                    hash="d11ee7beb14ef19dc5cd4d4024423f2a642e7726",
                    operation="DELETE",
                    pgid="pgtrigger_ignoreautofieldssnapshot_delete_297b6",
                    table="tests_ignoreautofieldssnapshotmodel",
                    when="AFTER",
                ),
            ),
        ),
    ]
